"""initial

Revision ID: 543a5a06fefa
Revises: 
Create Date: 2025-07-04 12:05:09.316073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '543a5a06fefa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_access_id'), table_name='feedback_access')
    op.drop_table('feedback_access')
    op.add_column('users', sa.Column('profile_image', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image')
    op.create_table('feedback_access',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('feedback_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('access_type', mysql.ENUM('comment', 'edit'), server_default=sa.text("'comment'"), nullable=True),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], name=op.f('feedback_access_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('feedback_access_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_feedback_access_id'), 'feedback_access', ['id'], unique=False)
    # ### end Alembic commands ###
